---
# tasks file for openovpnc_client

- name: Checking for Linux Ubuntu {{ovpnc_os_dist_ver}}
  fail: msg='This is not Linux Ubuntu {{ovpnc_os_dist_ver}} (required {{ovpnc_os_dist}} {{ovpnc_os_dist_ver}})'
  when: ansible_distribution != '{{ovpnc_os_dist}}' or ansible_distribution_major_version != '{{ovpnc_os_dist_ver}}'

- name: openvpn client - installing packages {{ovpnc_inst_packages}}
  apt:
    name: '{{ovpnc_inst_packages}}'
    state: present
  become: yes

- name: Checking that file exists - {{ovpnc_client_conf}}
  stat: path='{{ovpnc_client_conf}}'
  register: rc_ovpnc_client_conf

- include: conf_gen.yml
  when: ovpnc_conf_gen == true and rc_ovpnc_client_conf.stat.exists == false

- name: openvpn client - creating {{ovpnc_client_conf}}
  template: src="{{ item }}.j2" dest="/{{ item }}.conf" mode=400
  with_items:
  - 'etc/openvpn/{{ovpnc_client_name}}'
  become: yes
#  register: rc_ovpnc_conf_create
  when: rc_ovpnc_client_conf.stat.exists == false
  notify:
    - Restarting service - openvpn@{{ovpnc_client_name}}

#- fail:

- name: Enabling and running service - openvpn@{{ovpnc_client_name}}
  systemd: name='openvpn@{{ovpnc_client_name}}' state=started enabled=yes
#  when: rc_ovpnc_conf_create.changed
