---
# tasks file for ovpnc

- name: Checking for Linux {{ovpnc_os_dist}} {{ovpnc_os_dist_ver}}
  fail: msg='This is not Linux {{ovpnc_os_dist}} {{ovpnc_os_dist_ver}}'
  when: ansible_distribution_major_version != r_ovpnc_os_dist_ver.stdout

- name: openvpn client - installing packages {{ovpnc_inst_packages}}
  apt:
    name: '{{ovpnc_inst_packages}}'
    state: present
  become: yes

- name: Checking that file exists - {{ovpnc_client_conf}}
  stat: path='{{ovpnc_client_conf}}'
  register: rc_ovpnc_client_conf

- include: conf_gen.yml
  when: ovpnc_conf_gen == true and rc_ovpnc_client_conf.stat.exists == false


#- debug: msg='{{rc_date.stdout_lines}}'

- name: Getting current Unix time
  shell: date +'%s'
  register: rc_date

- name: Creating temporary file {{ovpnc_tmp}}.{{rc_date.stdout}}
  template: src="{{ item }}.j2" dest="{{ovpnc_tmp}}.{{rc_date.stdout}}" mode=400
  with_items:
  - 'etc/openvpn/{{ovpnc_client_name}}'
  become: yes
  when: rc_ovpnc_client_conf.stat.exists == true

- name: Comparing {{ovpnc_client_conf}} and {{ovpnc_tmp}}.{{rc_date.stdout}}
  shell: diff '{{ovpnc_client_conf}}' '{{ovpnc_tmp}}.{{rc_date.stdout}}'
  register: rc_diff
  become: yes
  when: rc_ovpnc_client_conf.stat.exists == true
  ignore_errors: true

#- debug: msg='rc_ovpnc_client_conf.stat={{rc_ovpnc_client_conf.stat}}'
#- debug: msg='rc_diff={{rc_diff}}'

- name: Moving {{ovpnc_client_conf}} to {{ovpnc_client_conf}}.{{rc_date.stdout}}
  command: mv '{{ovpnc_client_conf}}' '{{ovpnc_client_conf}}.{{rc_date.stdout}}'
  when: rc_ovpnc_client_conf.stat.exists == true and rc_diff.rc != 0
  become: yes

- name: Moving {{ovpnc_tmp}}.{{rc_date.stdout}} to {{ovpnc_client_conf}}
  command: mv '{{ovpnc_tmp}}.{{rc_date.stdout}}' '{{ovpnc_client_conf}}'
  when: rc_ovpnc_client_conf.stat.exists == true and rc_diff.rc != 0
  become: yes
  notify:
    - Restarting service - openvpn@{{ovpnc_client_name}}

- name: Creating {{ovpnc_client_conf}}
  template: src="{{ item }}.j2" dest="/{{ item }}.conf" mode=400
  with_items:
  - 'etc/openvpn/{{ovpnc_client_name}}'
  become: yes
  when: rc_ovpnc_client_conf.stat.exists == false or rc_diff.rc != 0
  notify:
    - Restarting service - openvpn@{{ovpnc_client_name}}

- name: Enabling and running service - openvpn@{{ovpnc_client_name}}
  systemd: name='openvpn@{{ovpnc_client_name}}' state=started enabled=yes
